[package]
name = "compression"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1", features = ["full"] }